### PR TITLE
WIP: create a mechanism of using custom configuration with docker-compose

### PR DESCRIPTION
**Pull request by paulbrodner**
SEARCH-1124: Design the approach of using custom configuration on docker-compose - for testing purposes 
SEARCH-1126: testing the approach with spellcheck enabled

### CODE REVIEW

**Comment by paulbrodner** [comment]
@tpage-alfresco @tunaaksoy @meenalbhave  checkout the implementation:
* we have a "**custom**" folder that will collect all future settings, like all settings for "[spellcheck](https://github.com/Alfresco/SearchServices/tree/feature/SEARCH-1118-enable-custom-configuration/packaging/src/docker/6.x/custom/spellcheck)" 
* in "**custom**" folder you can have other settings, like "ssh-enabled" - that will group all shell scripts to enable ssl (you need to create those)
* at runtime, you can pass the `SCRIPTS_FOLDER=ssh-enabled` for [docker-compose.custom.yml](https://github.com/Alfresco/SearchServices/blob/feature/SEARCH-1118-enable-custom-configuration/packaging/src/docker/6.x/docker-compose.custom.yml)

Checkout the [README.md](https://github.com/Alfresco/SearchServices/blob/feature/SEARCH-1118-enable-custom-configuration/packaging/src/docker/6.x/README.md) for more info.

For testing, I've search in Share the word "alfrezco" that will return results with spellcheck enabled.

**Comment by tunaaksoy** [comment]
I had a different approach in mind. I'll take a proper look at your solution when I get a bit more time.

**Comment by tunaaksoy** [comment]
Paul, can you fix your branch please? It makes the review very difficult. Maybe it's easier to create a new branch and apply your changes to that one.

**Comment by tunaaksoy** [comment]
So, the most simple solution is to have a modified version of shared.properties and copy that file (if it exists) and override the original one whilst building the docker image. There are a couple of things we need to consider in that case. Do we really need to build a custom docker image? It looks a bit overkill to me. Maybe we should discuss about this and try to find an easier solution together.

**Comment by paulbrodner** [comment]
The solution will be added in the BuildScripts(already there it will be demoed today), I've showed the solution to Meenal and Sri.
Anyway this is related to QA work only, Meenal will be the person that will use it often.

So I think I can close this pull request.

P.S. I didn't wanted to use a modified version of shared.properties because I need to keep track from original file.  The current solution will only enable some small granular changes.

**Pull request closed without merging**
