### PR TITLE
[MNT-23250] minTxnId is used is place of hardcoded

### PR DESCRIPTION
**Pull request by code4uuuu**
https://alfresco.atlassian.net/browse/MNT-23250

### CODE REVIEW

**Review by aborroy — CHANGES_REQUESTED** [review]
At least one test is required to verify the change is working as expected.

**Comment by code4uuuu** [comment]
> At least one test is required to verify the change is working as expected.

Added testcase for the code change but it was a private method to be tested so we could not assert transaction id boundaries however we have executed the test for the entire method from which it was getting called.

**Review by aborroy — APPROVED** [review]
LGTM

**Review by suneet-gupta — APPROVED** [review]
LGTM

**Pull request merged**
