### PR TITLE
[SEARCH-1509] ContentTracker documentation + diagrams

### PR DESCRIPTION
**Pull request by agazzarini**
The PR contains 

- a new folder /doc/trackers
- a document which explains the ContentTracker and the Trackers Subsystem
- UML diagrams

### CODE REVIEW

**Comment by tpage-alfresco** [comment]
LGTM. Thanks Andrea for writing this up so thoroughly!

**Comment by michaelsuzukisagi** [comment]
Looks good, may want to clarify on content tracker sequence diagram what collections we are iterating over, e.g dirty vs new etc

**Comment by agazzarini** [comment]
> Looks good, may want to clarify on content tracker sequence diagram what collections we are iterating over, e.g dirty vs new etc

Arghhh @michaelsuzukisagi  just merged! I will update the diagram and the re-submit the change

**Comment by michaelsuzukisagi** [comment]
you can work on master for docs changes.
________________________________

**Pull request merged**
